### ISSUE TITLE
Favicon.

### ISSUE THREAD

**Issue by soarn** [brtcoin/britecoin.github.io#1]
[](https://realfavicongenerator.net)
# I would suggest using realfavicongenerator for your site, because favicons lit af fam.  

~~im not a bot, 9i'm literally the guy who pinged you in the goldmine discord server.~~

**Comment by C0D2D** [comment]
lmao props to you for opening this issue on my repo lol. I am adding a favicon soon to the project's website also thanks for telling me about realfavicongenerator it will likely be useful later on.
